name = "codex-reset-monitor"
main = "src/index.js"
compatibility_date = "2026-09-24"

[[kv_namespaces]]
binding = "CODEX_STATE"
id = "49c67ed97f014efe81df1a10a4df797e"

[triggers]
crons = [ "* * * * *" ]
